services:
  frontend:
    image: ghcr.io/joaoppassos/jobapplyfrontend:latest
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL}
    restart: always
    ports:
      - "5173:5173"
